BEGIN;

DROP TABLE IF EXISTS styles CASCADE;

DROP TYPE IF EXISTS style_type CASCADE;

DROP TABLE IF EXISTS connections CASCADE;

DROP TABLE IF EXISTS nodes CASCADE;

DROP TABLE IF EXISTS projects CASCADE;

DROP TABLE IF EXISTS users CASCADE;

COMMIT;