// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type Mutation struct {
}

type Node struct {
	Value    *string `json:"value,omitempty"`
	ParentID *string `json:"parentId,omitempty"`
}

type NodeLevelConnection struct {
	TotalCount *int32        `json:"totalCount,omitempty"`
	NodeLevels []*NodeOutput `json:"nodeLevels,omitempty"`
	PageInfo   *PageInfo     `json:"pageInfo"`
}

type NodeOutput struct {
	ID       string         `json:"id"`
	Value    *string        `json:"value,omitempty"`
	ParentID *string        `json:"parentId,omitempty"`
	Styles   []*StyleOutput `json:"styles"`
}

type PageInfo struct {
	StartCursor *string `json:"startCursor,omitempty"`
	EndCursor   *string `json:"endCursor,omitempty"`
	HasNextPage bool    `json:"hasNextPage"`
}

type Project struct {
	Name   string `json:"name"`
	UserID string `json:"userId"`
}

type ProjectInfoConnection struct {
	TotalCount *int32               `json:"totalCount,omitempty"`
	Projects   []*ProjectInfoOutput `json:"projects,omitempty"`
	PageInfo   *PageInfo            `json:"pageInfo"`
}

type ProjectInfoOutput struct {
	ID         string    `json:"id"`
	Name       string    `json:"name"`
	UserID     string    `json:"userId"`
	CreatedAt  time.Time `json:"createdAt"`
	ModifiedAt time.Time `json:"modifiedAt"`
}

type Query struct {
}

type Style struct {
	NodeID string `json:"nodeId"`
	Type   string `json:"type"`
	Value  string `json:"value"`
}

type StyleOutput struct {
	NodeID    string `json:"nodeId"`
	StyleType string `json:"styleType"`
	Style     string `json:"style"`
}

type User struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type UserOutput struct {
	ID       string `json:"id"`
	Username string `json:"username"`
}
